// Code generated by "stringer -type=State"; DO NOT EDIT.

package servicer

import "strconv"

const (
	_State_name_0 = "CreatedStartingRunningStoppingStopped"
	_State_name_1 = "Unknown"
	_State_name_2 = "StatusQueryStatusNextStatusStateChange"
	_State_name_3 = "statusSubscribe"
)

var (
	_State_index_0 = [...]uint8{0, 7, 15, 22, 30, 37}
	_State_index_2 = [...]uint8{0, 11, 21, 38}
)

func (i State) String() string {
	switch {
	case 0 <= i && i <= 4:
		return _State_name_0[_State_index_0[i]:_State_index_0[i+1]]
	case i == 24576:
		return _State_name_1
	case 32768 <= i && i <= 32770:
		i -= 32768
		return _State_name_2[_State_index_2[i]:_State_index_2[i+1]]
	case i == 49152:
		return _State_name_3
	default:
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
